// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eovbmghbnabknnnytmcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvdmJtZ2hibmFia25ubnl0bWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjkzNDYsImV4cCI6MjA1ODMwNTM0Nn0.ZOwj8jQvkqvQ3y2tKASsgTz5R3yDHi2cRFO_XStaTYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);